---
- name: is start up focuslight with port 9400?
  command: lsof -i:9400 
  register: is_running_focuslight_05
  ignore_errors: True
  tags: focuslight

- name: docker run focuslight to port 9400.
  command: docker run -p 9400:80 -v /var/focuslight/5/:/root/focuslight/data -d futoase/docker-focuslight 
  when: is_running_focuslight_05|failed
  notify: restart nginx
